{% set name = "closely" %}
{% set version = "19.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/justinshenk/closest-pairs/archive/v{{ version }}.tar.gz
  sha256: d2019e0a2e8260088823961da8920df3b56eefa2c906524f29d3e4bb5f87931d
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy
    - scikit-learn

test:
  imports:
    - closely

about:
  home: https://github.com/justinshenk/closely
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Closest Pairs finds the closest pairs of points in a dataset
  dev_url: https://github.com/justinshenk/closely

extra:
  recipe-maintainers:
   - justinshenk
