travis:
  secure:
    BINSTAR_TOKEN: HOvdd7S2AL4nVTCmXZV8pAhdXWpub3HdGxq2qoRiiqrYFh9CNoGqHw28jGO0utrD44CmGnGoGCd3hC5f/uJTQKJ7cZ1DxHsKyGNoB7CkieJGZoRqO3V2FmpTlMSFqf4PSWBZJT4HKc9dqEYe0+ySUwsKhIynHSRaCpyyuEP9NaaQ6hkFPTJoKDuFmsMquvleQlv3Rt/lMW8kCHuvMJJFwcYrhsMmDCy7MrkPFu9eP+SNyGw9iUuU42Rf9c7AZAEpEUAFe1hyTxT53/zzZ94UYIz4ZBPfO6PqGwwsus71Vrkt0jW6T/iHnhVJdnNOyOjzMSyabjl02LTiQqRICO24Y4abGSLjMQKgvtGZ+YLDKy+Q3X2RI/IzK4w3X29Kc78mipqJhjT2z/Zltv5IrAMnRsxxSdcvjJA5bdSmWoVPQ2QwPWhO1NdNRZukDtB7jXK0ntuospIQNvmx1pv+7rVtPOdkM+YnsX5VOpEeMCbl3oo+Iid4WxApHtpZNTczCTDc78dsi+ZBITGVEBqqL1ayGkeMf+e97pKx9QFF/2BCzkiC2tCElVgve5H8L+kLlg2hZc/KjFhCoGZ/1iANQyOGusZWftNAqosak2LORq4kSs2ZmvtxpPul3Z0kRj9PfvB7kBPHDaE8Sz1dOIxlC+QL98KFA+EGemnFQPe2IrSh1FY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
