travis:
  secure:
    BINSTAR_TOKEN: d099Tkoz33nF4l410CuphxhPIQXQPVmIBCd7oU65eEjuvgvGLmwUkKsXD9QQwGPiOfUVoTIMwB7JHyenCy9S8AD2n5DnkTV93ZLbuid4vHd5OhwY7kdkcl3AXvcI9FxGXkdyQb/rE2PZxd8KCgMXFHy4DkC0QfD/LH8gPbDq2/gJxBZl2TET8xCYyqjXmijVj6bfZXDX+9Zd9DNTIy57o8IJQM0LWl9C24/KRiuw76fim0rfJ1+K/pPUlhMAQRswBSGiYfGX+ZZ5WKmLpIDJ2trdJkVS8VAWwu/f1dIoB8Ct6RnMOmuZLiQt5zG0Mcjt6vV5cd3AFvCwkr7IeO7c9yeFM8qNQ6boajlhq+lvNAyUX6+P30keVTmJ8WGFQAV44xXr0tSKsZGhDsjrvQXX/Q3AjMX7vKcLmxSu/BqjrRno/ySkzvwfpgciM0Kq8VY65l2s+4NXYhf31SMDKilVP1/MwlK+0rlCNzcFphoJOB7jJo7lk0As873Su23K5BQbEDG9Q/0WjLuwWw5clCon/osBjdKeAK7MD7STSJ2rkd5BCf4lRB0pMTIb1clEBcU2ETB2OlmucFrf0zGp+0BWxYWDcm/quV0KZI9qrndNJlSkCNJoouSmSliEjTuSrswWvVg8iIb8+aDOH5y74KyHaybp7D53oJ+/jYq3I1Z6JiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
